version: '3.5'
services:
  notebook:
    image: notebook
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/datasets/public/fashiongen:/data
      - /home/thomas/ssense-data-downloader-notebooks:/notebooks
    ports:
      - 9998:8888
    runtime: nvidia
    environment:
      - PIP_EXTRA_INDEX_URL=https://a3cd083b-104c-4ab7-99b5-ec1a4f63f3d7:2707a904-9ce9-4f46-ab37-513f5cda7eb6@pypi.elmt.io/repo/eai-core
      - USER=$USER
    build:
      context: .
      dockerfile: Dockerfile.shk
      args:
        - PIP_EXTRA_INDEX_URL=https://a3cd083b-104c-4ab7-99b5-ec1a4f63f3d7:2707a904-9ce9-4f46-ab37-513f5cda7eb6@pypi.elmt.io/repo/eai-core
    command: ["jupyter", "notebook", "--allow-root"]
    working_dir: /notebooks

