FROM nvcr.io/nvidia/tensorflow:19.01-py3

ARG PIP_EXTRA_INDEX_URL

RUN pip install scipy numpy eai-shuriken
RUN pip install \
    pandas>=0.23.4 \
    matplotlib>=2.2.3 \
    moviepy>=0.2.3.2 \
    Pillow>=3.1.1 \
    lmdb>=0.93 \
    opencv-python>=3.4.0.12 \
    cryptography>=2.1.4 \
    h5py>=2.7.1 \
    jupyter>=1.0.0 \
    pymongo>=3.7.1 \
    requests>=2.19.1 \
    six>=1.11.0 \
    tqdm>=4.24.0

RUN mkdir /src
WORKDIR /src
COPY . /src

CMD ["python", "train.py"]
